### ISSUE TITLE
Create mirror in IEEE SA OpenSource

### ISSUE THREAD

**Issue by rampmaster** [ADockhorn/SummerSchoolsConnect#1]
Please create a mirror on IEEE SA OpenSource (opensource.ieee.org) so that the project is not lost. I recommend to report it to vTools Labs (https://ieee-collabratec.ieee.org/app/workspaces/9057/vTools-Labs/activities)

**Comment by ADockhorn** [comment]
Hi, thanks for the suggestion. This is a project that is part of our Volunteer Leadership Training Program. In this program, we form teams of 6 people and each team submits one project to benefit IEEE. We developed a small prototype to share our vision for a summer school search and registration platform. As soon as the project has been reviewed by the program committee, we can approach reporting this tool in IEEE SA OpenSource, vTool Labs and hopefully establish it within IEEE.

**Comment by rampmaster** [comment]
Thank you very much for the prompt reply. I had the intention of incorporating it in the new website of region 9. Unfortunately, from what you inform me, I will not be able to implement it with the time available.

**Comment by ADockhorn** [comment]
That's likely hard to do fast with the given prototype since the whole site is a completely static implementation. However, in the Volt program, the different proposals will be evaluated and considered for implementation with the IEEE. In case our project gets chosen, we will be searching for a partner unit at IEEE. This could either be on a IEEE society level or a regional level.
